---
apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-cert
  namespace: vaultwarden
spec:
  secretName: wildcard-groovyreserve-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.o1.groovyreserve.com"
  dnsNames:
  - "*.o1.groovyreserve.com"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/vaultwarden
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: vaultwarden-data-pv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  namespace: vaultwarden
data:
  DOMAIN: "https://bitwarden.o1.groovyreserve.com"

  # SSO_ENABLED: "true"
  # SSO_ONLY: "true"
  # SSO_SCOPES: "email profile offline_access"
  # SSO_AUTHENTIK_URL: "http://authentik-server.authentik/application/o/vaultwarden/"
  # SSO_CLIENT_ID: "vaultwarden"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:1.35.1
        ports:
        - containerPort: 80
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vaultwarden-secrets
              key: database_url
        envFrom:
        - configMapRef:
            name: vaultwarden-config
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vaultwarden-data
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  selector:
    app: vaultwarden
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  ingressClassName: traefik
  tls:
    - hosts:
      - bitwarden.o1.groovyreserve.com
      secretName: wildcard-groovyreserve-com
  rules:
    - host: bitwarden.o1.groovyreserve.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: vaultwarden
                port:
                  number: 80
