# Trial at keeping values held in the config
open-webui:
  replicaCount: 1
  image:
    tag: "latest"
  ingress:
    enabled: true
    hosts:
      - host: open-webui.local
        paths:
          - path: /
            pathType: prefix

ollama:
  enabled: false

persistence:
  enabled: true
  size: 10Gi