# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.
{ pkgs, lib }:

let
  inherit (pkgs.stdenv) isDarwin isLinux isi686 isx86_64 isAarch32 isAarch64;
  vscode-utils = pkgs.vscode-utils;
  merge = lib.attrsets.recursiveUpdate;
in
merge
  (merge
    (merge
      (merge
      {
        "robbowen"."synthwave-vscode" = vscode-utils.extensionFromVscodeMarketplace {
          name = "synthwave-vscode";
          publisher = "robbowen";
          version = "0.1.18";
          sha256 = "0f52fbk3c8r0y2j9kcg5a95rz40650lh1dccz17hhf1ja0ymmvlr";

        };
        "eliverlara"."andromeda" = vscode-utils.extensionFromVscodeMarketplace {
          name = "andromeda";
          publisher = "eliverlara";
          version = "1.8.2";
          sha256 = "05rrgvpqngfrwa289jw5kff9ns52ba24nzrfcl1rvf55w9gb7gxs";

        };
        "wicked-labs"."wvsc-serendipity" = vscode-utils.extensionFromVscodeMarketplace {
          name = "wvsc-serendipity";
          publisher = "wicked-labs";
          version = "1.66.0";
          sha256 = "1l484q90kq5yzfxbaz7bfdiqbick92g70gakxbmcxq48ign85wlg";

        };
        "ispapp"."mikrotik-routeros-script-tools" = vscode-utils.extensionFromVscodeMarketplace {
          name = "mikrotik-routeros-script-tools";
          publisher = "ispapp";
          version = "1.1.0";
          sha256 = "1glbl3cdmq8jw1i46v1m80h3x2fkyk2h1fxr68vkj1bikcpxcmhf";

        };
        "jamiewoodio"."cisco" = vscode-utils.extensionFromVscodeMarketplace {
          name = "cisco";
          publisher = "jamiewoodio";
          version = "1.9.1";
          sha256 = "0hqmpjpaxyhmxskarcfrh3w2kcsjgr0cmc2bifp7qpi99glw2yq8";

        };
      }
        (lib.attrsets.optionalAttrs (isLinux && (isi686 || isx86_64)) { }))
      (lib.attrsets.optionalAttrs (isLinux && (isAarch32 || isAarch64)) { }))
    (lib.attrsets.optionalAttrs (isDarwin && (isi686 || isx86_64)) { }))
  (lib.attrsets.optionalAttrs (isDarwin && (isAarch32 || isAarch64)) { })