# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.
{ pkgs, lib }:

let
  inherit (pkgs.stdenv) isDarwin isLinux isi686 isx86_64 isAarch32 isAarch64;
  vscode-utils = pkgs.vscode-utils;
  merge = lib.attrsets.recursiveUpdate;
in
merge
  (merge
    (merge
      (merge
      {
        "alecghost"."tree-sitter-vscode" = vscode-utils.extensionFromVscodeMarketplace {
          name = "tree-sitter-vscode";
          publisher = "alecghost";
          version = "0.2.1";
          sha256 = "1c4gfpdqm9rh05lr7m3j1vw34arzh5z1j0xrm0szy6hkra4y6i1w";

        };
        "ispapp"."mikrotik-routeros-script-tools" = vscode-utils.extensionFromVscodeMarketplace {
          name = "mikrotik-routeros-script-tools";
          publisher = "ispapp";
          version = "1.1.0";
          sha256 = "1glbl3cdmq8jw1i46v1m80h3x2fkyk2h1fxr68vkj1bikcpxcmhf";

        };
        "jamiewoodio"."cisco" = vscode-utils.extensionFromVscodeMarketplace {
          name = "cisco";
          publisher = "jamiewoodio";
          version = "1.9.1";
          sha256 = "0hqmpjpaxyhmxskarcfrh3w2kcsjgr0cmc2bifp7qpi99glw2yq8";

        };
        "keifererikson"."nightfox" = vscode-utils.extensionFromVscodeMarketplace {
          name = "nightfox";
          publisher = "keifererikson";
          version = "0.0.14";
          sha256 = "09kp1ss8plg5l9mifnkk4dyf1g2immfr6gymzcaysdrzqwj8m48i";

        };
        "metaphore"."kanagawa-vscode-color-theme" = vscode-utils.extensionFromVscodeMarketplace {
          name = "kanagawa-vscode-color-theme";
          publisher = "metaphore";
          version = "0.5.0";
          sha256 = "1l2y5ch6im9qff15kqlxf4j0wxbzl354pqrbby5ybbz76pbjzkis";

        };
        "michalpopek"."dayfox-vsc" = vscode-utils.extensionFromVscodeMarketplace {
          name = "dayfox-vsc";
          publisher = "michalpopek";
          version = "0.1.0";
          sha256 = "16wmicdp35nm7gr098mibgclwqap7nr5nmnq8agnp00paq80aabi";

        };
        "mthierman"."theme-flexoki" = vscode-utils.extensionFromVscodeMarketplace {
          name = "theme-flexoki";
          publisher = "mthierman";
          version = "0.0.9";
          sha256 = "0dwk60jlz1il9qs311ylv44d9sjaxa4faayhl546zzzgj25r9ki9";

        };
        "srl-labs"."vscode-containerlab" = vscode-utils.extensionFromVscodeMarketplace {
          name = "vscode-containerlab";
          publisher = "srl-labs";
          version = "0.12.0";
          sha256 = "0x2m9v20yj5s6pajrw1pirdcd64f878x1bfsqbbqyk1rv98xziw8";

        };
        "wicked-labs"."wvsc-serendipity" = vscode-utils.extensionFromVscodeMarketplace {
          name = "wvsc-serendipity";
          publisher = "wicked-labs";
          version = "1.66.0";
          sha256 = "1l484q90kq5yzfxbaz7bfdiqbick92g70gakxbmcxq48ign85wlg";

        };
        "zhuangtongfa"."material-theme" = vscode-utils.extensionFromVscodeMarketplace {
          name = "material-theme";
          publisher = "zhuangtongfa";
          version = "3.19.0";
          sha256 = "1z3wiacb2m7hvpfhn6qs710lsaxpy7c56jbjckccvqi705w9firb";

        };
      }
        (lib.attrsets.optionalAttrs (isLinux && (isi686 || isx86_64)) { }))
      (lib.attrsets.optionalAttrs (isLinux && (isAarch32 || isAarch64)) { }))
    (lib.attrsets.optionalAttrs (isDarwin && (isi686 || isx86_64)) { }))
  (lib.attrsets.optionalAttrs (isDarwin && (isAarch32 || isAarch64)) { })
