vscode_version = "1.99.3"

extensions = [
    # Themes
    "wicked-labs.wvsc-serendipity",
    "keifererikson.nightfox",
    "metaphore.kanagawa-vscode-color-theme",
    "ddiu8081.moegi-theme",
    "sainnhe.everforest",

    # Editor Tools
    "AlecGhost.tree-sitter-vscode",

    # Networking Tools
    "jamiewoodio.cisco",
    "ispapp.mikrotik-routeros-script-tools",
    "srl-labs.vscode-containerlab",
]
