---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-media-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/authentik
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: authentik-media-pv
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authentik
  namespace: authentik
spec:
  repo: https://charts.goauthentik.io
  chart: authentik
  targetNamespace: authentik
  valuesContent: |-
    authentik:
      secret_key: file:///authentik-secrets/secret_key
      persistence:
        media:
          enabled: true
          existingClaim: authentik-media
      postgresql:
        host: 10.42.0.1 
        port: 5432
        name: authentik
        user: authentik
        password: file:///authentik-secrets/postgres_password
    server:
      volumes:
        - name: authentik-secrets
          secret:
            secretName: authentik-secrets
      volumeMounts:
        - name: authentik-secrets
          mountPath: /authentik-secrets
          readOnly: true
    worker:
      volumes:
        - name: authentik-secrets
          secret:
            secretName: authentik-secrets
      volumeMounts:
        - name: authentik-secrets
          mountPath: /authentik-secrets
          readOnly: true

