---
name: CI
"on":
  push:
    branches: [master, main]
    paths:
      - "flake.*"
      - "modules/**"
      - "packages/**"
      - ".config/**"
      - ".github/workflows/**"
  pull_request:
    branches: [master, main]
    paths:
      - "flake.*"
      - "modules/**"
      - "packages/**"
      - ".config/**"
      - ".github/workflows/**"
  workflow_dispatch:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: ${{ matrix.check.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - name: deadnix
            cmd: nix develop --command deadnix --fail --exclude _sources/ .
          - name: statix
            cmd: nix develop --command statix check -c .config/statix.toml .
          - name: typos
            cmd: nix develop --command typos -c .config/typos.toml .
          - name: treefmt
            cmd: |
              nix develop --command treefmt \
              --ci --config-file .config/treefmt.toml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run ${{ matrix.check.name }}
        run: ${{ matrix.check.cmd }}
  flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Flake
        run: nix flake check -L
